---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodejs-develop-s01-sa
imagePullSecrets:
  - name: quay-credentials  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nodejs-develop-s01-sa-admin
subjects:
- kind: ServiceAccount
  name: nodejs-develop-s01-sa 
  namespace: nodejs-develop-s01-develop
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
