apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  backstage.io/kubernetes-id: nodejs-develop-s01

resources:
#  - project.yaml
#  - rolebindings.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
  - app-sa.yaml
#  - link-image-pull-secret-job.yaml
